image: rambabusaravanan/firebase

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-prod:
  stage: deploy
  only:
    - TMDT-release
    - HTTT-release
  script:
    - npm i
    - npm run build:ci
    - firebase use react-research-bdd27 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
