version: 2
jobs:
    build:
        docker:
            - image: rambabusaravanan/firebase

    filters:
        branches:
            only:
                - TMDT

    working_directory: ~/src

    steps:
        - checkout

        - run: npm install

        - run: npm run build:ci

        - run: firebase use react-research-bdd27 --token $FIREBASE_TOKEN

        - run: firebase deploy --only hosting -m "Deploy by Circle CI" --token $FIREBASE_TOKEN

        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

