version: 2
jobs:
    build:
        docker:
            - image: rambabusaravanan/firebase

        build:
            branches:
                only:
                    - master
                    - tmdt-release
                    - portfolio-release

        working_directory: ~/src

        steps:
            - checkout

            - run: ls

            - run: npm install

            - run: npm run build:ci

            - run: ls

            - run: ls dist

            - run: firebase use react-portfolio-fe7fb --token $FIREBASE_TOKEN

            - run: firebase deploy --only hosting -m "Deploy by Circle CI" --token $FIREBASE_TOKEN

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

